# -*- coding: utf-8 -*-
"""Networks/Quant Finance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LK0CmwQtzn6yH5y6P9oZb8kHgVJ-aACo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

import torch
import torch.nn as nn
import torch.optim as optim

!pip uninstall torch-scatter torch-sparse torch-geometric torch-cluster  --y
!pip install torch-scatter -f https://data.pyg.org/whl/torch-{torch.__version__}.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-{torch.__version__}.html
!pip install torch-cluster -f https://data.pyg.org/whl/torch-{torch.__version__}.html
!pip install git+https://github.com/pyg-team/pytorch_geometric.git

from torch_geometric.data import Data
from torch_geometric.nn import GCNConv

"""# Economic Networks Summer School — Tutorial

## Networks of multivariate financial data and graph-based forecasting

We look at an example of multivariate daily futures data across various asset classes such as equity index, currency, fixed-income and commodity futures.

Note that '6B' and '6E' (GBPUSD and EURUSD), are renamed 'B6' and 'E6'. Everything else is as usual, e.g. ES (S&P 500), NQ (Nasdaq), etc.


### Step 1. Get dataset
"""

# Read the dataset
data = pd.read_csv("./merged_multivariate.csv")

data.drop("flag", axis=1, inplace=True)  # remove "flag" column
data['date'] = pd.to_datetime(data['date'])
data.head()

"""Note that the data has been supplemented with a new column called 'vol' which contains the Parkinson volatility computed from the daily high and low prices.

## Exercise 1

Pivot the data to a wide table of open or close price with each column being an asset. Compute and visualise the correlation matrix. Are there any hierarchical structures?
"""

import seaborn as sns
from scipy.cluster.hierarchy import linkage, dendrogram
from scipy.spatial.distance import pdist, squareform

# 1. Pivot the data to a wide table of close prices with each column being an asset
data_pivot_close = data.pivot(index='date', columns='symbol', values='close')

# Display the first few rows of the pivoted data
print("Pivoted Data (Close Prices):")
print(data_pivot_close.head())
print("\n")

# 2. Compute the correlation matrix
correlation_matrix = data_pivot_close.corr()

# Display the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix.head())
print("\n")

# 3. Visualize the correlation matrix
plt.figure(figsize=(14, 12))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Asset Close Prices', fontsize=16)
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.show()

# 4. Compute and visualize hierarchical structures using a dendrogram
# Handle potential NaNs in correlation matrix (e.g., if an asset has no variance)
# Fill with 0 for correlation (no linear relationship) or drop if problematic
correlation_matrix_cleaned = correlation_matrix.fillna(0)

# Calculate distance matrix (1 - absolute correlation) for hierarchical clustering
# Using 1 - abs(correlation) is common to measure dissimilarity
distance_matrix = 1 - np.abs(correlation_matrix_cleaned)

# Ensure the distance matrix is symmetric and has no NaNs for pdist/squareform
# We need the condensed distance matrix for linkage
# pdist expects a 2D array where rows are observations and columns are features.
# Here, we treat each asset's correlation profile as an observation.

# We can convert the square distance matrix to a condensed form
# If we pass correlation_matrix_cleaned directly to pdist, it computes pairwise distances between asset *vectors*.
# A common approach for correlation-based clustering is to use the existing correlation matrix to derive distances.
# Let's verify the input for linkage.

# Convert the square distance matrix to a condensed form suitable for linkage
dist_condensed = squareform(distance_matrix)

# Perform hierarchical clustering
# 'average' linkage method is a good general choice
linked = linkage(dist_condensed, method='average')

# Plot the dendrogram
plt.figure(figsize=(15, 8))
dendrogram(linked,
           orientation='top',
           labels=correlation_matrix_cleaned.columns.tolist(), # Ensure labels are from the cleaned matrix
           distance_sort='descending',
           show_leaf_counts=True)
plt.title('Hierarchical Clustering Dendrogram of Asset Correlations', fontsize=16)
plt.xlabel('Asset Symbol')
plt.ylabel('Distance (1 - |Correlation|)')
plt.show()

print("\nBased on the dendrogram, assets that are clustered together, especially at lower distance values, indicate a stronger hierarchical relationship or similarity in their price movements.")

"""

## Exercise 2

Construct and visualise various networks obtained from the data by thresholding the absolute value of the correlation. You can use the networkx library as imported above.

"""

import networkx as nx
import matplotlib.pyplot as plt

# Define a list of thresholds for the absolute correlation
thresholds = [0.8, 0.7, 0.6, 0.5]

# Get the list of asset symbols (nodes for our network)
asset_symbols = correlation_matrix_cleaned.columns.tolist()

for threshold in thresholds:
    print(f"\nCreating and visualizing network for absolute correlation threshold: {threshold}")

    # Create an adjacency matrix based on the threshold
    # We want to connect nodes if the absolute correlation between them is >= the threshold
    # Also, exclude self-loops (correlation of an asset with itself is always 1)
    adjacency_matrix = (np.abs(correlation_matrix_cleaned) >= threshold).astype(int)

    # Remove self-loops (diagonal elements)
    np.fill_diagonal(adjacency_matrix.values, 0)

    # Create a graph from the adjacency matrix
    G = nx.from_pandas_adjacency(adjacency_matrix, create_using=nx.Graph)

    # Remove isolated nodes (nodes with no connections)
    G.remove_nodes_from(list(nx.isolates(G)))

    if G.number_of_nodes() == 0:
        print(f"No connections found for threshold {threshold}. Skipping visualization.")
        continue

    # Visualize the graph
    plt.figure(figsize=(10, 8))
    pos = nx.spring_layout(G, k=0.8) # Position nodes using Fruchterman-Reingold force-directed algorithm

    # Draw nodes
    nx.draw_networkx_nodes(G, pos, node_size=700, node_color='lightblue')

    # Draw edges
    nx.draw_networkx_edges(G, pos, width=1.0, alpha=0.5, edge_color='gray')

    # Draw labels
    nx.draw_networkx_labels(G, pos, font_size=10, font_weight='bold')

    plt.title(f'Network of Assets (Absolute Correlation >= {threshold})', fontsize=15)
    plt.axis('off') # Hide axes
    plt.show()

"""## Challenge

Use a network constructed in Exercise 2 (you might want to ensure that this was done on the train data set) and build (a toy model) of a Graph Convolutional Network to forecast daily (Parkinson) volatility. You can use the torch_geometric library as imported above.

### Challenge: Build a GCN for Volatility Forecasting

This section addresses the challenge: using a network constructed from correlation to build a toy GCN model to forecast daily Parkinson volatility. We'll use the `torch_geometric` library for this.

First, we'll prepare our data, which involves splitting it into training and testing sets, and constructing the graph's `edge_index` based on the correlation matrix of the training data. This ensures our model learns from the relationships observed in the training period.
"""

# Ensure we have a consistent list of asset symbols from the correlation matrix cleaned earlier.
# This defines the order of nodes for our GCN.
asset_symbols = correlation_matrix_cleaned.columns.tolist()
num_nodes = len(asset_symbols)

# 1. Train/Test Split
# Assuming 'data' DataFrame is available and sorted by 'date'.
unique_dates = data['date'].unique()
num_dates = len(unique_dates)
train_split_idx = int(num_dates * 0.8)  # 80% for training
train_dates = unique_dates[:train_split_idx]
test_dates = unique_dates[train_split_idx:]

# Filter data for train and test periods
train_data_df = data[data['date'].isin(train_dates)].copy()
test_data_df = data[data['date'].isin(test_dates)].copy()

print(f"Training period from {train_dates.min()} to {train_dates.max()}")
print(f"Testing period from {test_dates.min()} to {test_dates.max()}")

# 2. Construct Graph (edge_index) from Training Data Correlation
# Pivot the training data to get close prices for correlation calculation
train_data_pivot_close = train_data_df.pivot(index='date', columns='symbol', values='close')

# Reindex to ensure all assets are in a consistent order and handle any missing ones for correlation calculation.
# Fill with NaNs first, then drop any columns that are entirely NaN (assets not present in train set).
# Then compute correlation and fill remaining NaNs (e.g., if an asset has no variance).
train_data_pivot_close_reindexed = train_data_pivot_close.reindex(columns=asset_symbols)
train_data_pivot_close_reindexed.dropna(axis=1, how='all', inplace=True)

# Update asset_symbols to reflect only assets present in the training data for graph construction
current_train_assets = train_data_pivot_close_reindexed.columns.tolist()

train_correlation_matrix = train_data_pivot_close_reindexed.corr().fillna(0)

# Define a threshold for creating edges in the graph
graph_threshold = 0.6  # This threshold can be tuned

# Create an adjacency matrix based on the absolute correlation threshold
adj_matrix = (np.abs(train_correlation_matrix) >= graph_threshold).astype(int)
np.fill_diagonal(adj_matrix.values, 0)  # Remove self-loops

# Convert adjacency matrix to edge_index (COO format) for torch_geometric
src_nodes = []
dst_nodes = []
for i in range(adj_matrix.shape[0]):
    for j in range(adj_matrix.shape[1]):
        if adj_matrix.iloc[i, j] == 1:
            src_nodes.append(i)
            dst_nodes.append(j)
edge_index = torch.tensor([src_nodes, dst_nodes], dtype=torch.long)

print(f"\nGraph constructed with {edge_index.shape[1]} edges based on training data correlation >= {graph_threshold}.")

"""Next, we'll prepare the data into `torch_geometric.data.Data` objects. Each object will represent a day, containing features for all assets on that day (`x`), the static graph structure (`edge_index`), and the target volatility for the next day (`y`)."""

from torch_geometric.data import Data

# Features to use for each node (asset) on a given day
features_list = ['open', 'high', 'low', 'close', 'vol']
num_features = len(features_list)

def create_gcn_dataset(df, dates, all_asset_symbols, edge_index, features_to_use):
    dataset = []
    # We iterate up to len(dates) - 1 because we need next day's 'vol' as target
    for i in range(len(dates) - 1):
        current_date = dates[i]
        next_date = dates[i+1]

        # Get features for current_date
        current_day_df = df[df['date'] == current_date].set_index('symbol')
        # Reindex to ensure all assets are present and in consistent order with the graph
        current_day_df = current_day_df.reindex(all_asset_symbols) # Use the list of assets from graph construction

        # Get target (volatility) for next_date
        next_day_df = df[df['date'] == next_date].set_index('symbol')
        next_day_df = next_day_df.reindex(all_asset_symbols)

        # Skip if any required data is missing for current or next day
        # For a robust solution, imputation could be used here.
        if current_day_df[features_to_use].isnull().values.any() or next_day_df['vol'].isnull().values.any():
            continue

        x = torch.tensor(current_day_df[features_to_use].values, dtype=torch.float)
        y = torch.tensor(next_day_df['vol'].values, dtype=torch.float)

        # Ensure x and y have the correct number of nodes
        if x.shape[0] != len(all_asset_symbols) or y.shape[0] != len(all_asset_symbols):
            print(f"Warning: Node count mismatch for date {current_date}. Skipping.")
            continue

        data_obj = Data(x=x, edge_index=edge_index, y=y)
        dataset.append(data_obj)
    return dataset

# Create training and testing datasets
train_dataset = create_gcn_dataset(train_data_df, train_dates, current_train_assets, edge_index, features_list)
test_dataset = create_gcn_dataset(test_data_df, test_dates, current_train_assets, edge_index, features_list)

print(f"Number of training graph samples: {len(train_dataset)}")
print(f"Number of testing graph samples: {len(test_dataset)}")

"""Now, we'll define a simple Graph Convolutional Network (GCN) model using `torch_geometric.nn.GCNConv`. This model will take node features and the graph structure as input and output a single predicted volatility value for each node (asset)."""

import torch.nn as nn
import torch.optim as optim
from torch_geometric.nn import GCNConv

class GCNVolatilityForecaster(torch.nn.Module):
    def __init__(self, num_features, hidden_channels):
        super().__init__()
        # First GCN layer: input_features -> hidden_channels
        self.conv1 = GCNConv(num_features, hidden_channels)
        # Second GCN layer: hidden_channels -> 1 (for single volatility output per node)
        self.conv2 = GCNConv(hidden_channels, 1)

    def forward(self, x, edge_index):
        # x has shape [num_nodes, num_features]
        # edge_index has shape [2, num_edges]
        x = self.conv1(x, edge_index)
        x = torch.relu(x) # Apply ReLU activation after the first layer
        x = self.conv2(x, edge_index)
        return x.squeeze(1) # Squeeze to [num_nodes] as we predict one value per node

print("GCN Model defined.")

"""Finally, we will train our GCN model using the prepared training dataset and evaluate its performance on the test set using Root Mean Squared Error (RMSE). We'll also visualize the predictions for a selected asset."""

from sklearn.metrics import mean_squared_error

# Hyperparameters for training
hidden_channels = 16  # Number of channels in the hidden layer
learning_rate = 0.01
epochs = 30

# Initialize the model, optimizer, and loss function
model = GCNVolatilityForecaster(num_features, hidden_channels)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss() # Mean Squared Error for regression task

print("Starting GCN model training...")
model.train() # Set the model to training mode
for epoch in range(epochs):
    total_loss = 0
    for data_sample in train_dataset: # Iterate through each daily graph sample
        optimizer.zero_grad()
        out = model(data_sample.x, data_sample.edge_index) # Forward pass
        loss = criterion(out, data_sample.y) # Compute loss
        loss.backward() # Backpropagation
        optimizer.step() # Update model parameters
        total_loss += loss.item()

    avg_loss = total_loss / len(train_dataset)
    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch+1}/{epochs}, Loss: {avg_loss:.6f}')

print("\nGCN model training finished. Starting evaluation...")
model.eval() # Set the model to evaluation mode
predictions = []
true_values = []

with torch.no_grad(): # Disable gradient calculations during evaluation
    for data_sample in test_dataset:
        out = model(data_sample.x, data_sample.edge_index)
        predictions.append(out.cpu().numpy()) # Store predictions
        true_values.append(data_sample.y.cpu().numpy()) # Store true values

# Concatenate all predictions and true values
predictions = np.concatenate(predictions)
true_values = np.concatenate(true_values)

# Calculate Root Mean Squared Error (RMSE)
rmse = np.sqrt(mean_squared_error(true_values, predictions))
print(f'Test RMSE: {rmse:.4f}')

# Reshape predictions and true_values back to (num_samples, num_nodes) for easy indexing
num_test_samples = len(test_dataset)
predictions_reshaped = predictions.reshape(num_test_samples, len(current_train_assets))
true_values_reshaped = true_values.reshape(num_test_samples, len(current_train_assets))

# Visualize predictions vs true values for selected assets
assets_to_visualize = ['ES', 'B6', 'E6'] # Add more assets here as desired

for asset in assets_to_visualize:
    if asset in current_train_assets:
        asset_idx = current_train_assets.index(asset)

        asset_preds = predictions_reshaped[:, asset_idx]
        asset_true = true_values_reshaped[:, asset_idx]

        plt.figure(figsize=(14, 7))
        plt.plot(asset_true, label=f'True Volatility ({asset})')
        plt.plot(asset_preds, label=f'Predicted Volatility ({asset})', alpha=0.7)
        plt.title(f'GCN Volatility Forecast for {asset} on Test Set')
        plt.xlabel('Time Steps (Test Data)')
        plt.ylabel('Volatility')
        plt.legend()
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.show()
    else:
        print(f"Asset '{asset}' not found in the training assets for detailed visualization.")

"""### Baseline Model: Naive Volatility Forecast

To evaluate the effectiveness of our GCN, let's compare its performance against a simple baseline model. A common naive baseline for time series forecasting is to assume that the next observation will be the same as the current observation. In our case, this means predicting that tomorrow's volatility for an asset will be equal to today's volatility for that asset.
"""

# Initialize a list to store naive baseline predictions
naive_predictions = []
naive_true_values = []

# The features_list includes 'vol' at index 4
vol_feature_idx = features_list.index('vol')

for data_sample in test_dataset:
    # Naive prediction: next day's volatility is today's volatility
    # The 'vol' feature for the current day is in data_sample.x
    current_day_volatility = data_sample.x[:, vol_feature_idx]
    naive_predictions.append(current_day_volatility.cpu().numpy())
    naive_true_values.append(data_sample.y.cpu().numpy())

# Concatenate all naive predictions and true values
naive_predictions = np.concatenate(naive_predictions)
naive_true_values = np.concatenate(naive_true_values)

# Calculate RMSE for the naive baseline
naive_rmse = np.sqrt(mean_squared_error(naive_true_values, naive_predictions))

print(f'Naive Baseline RMSE: {naive_rmse:.4f}')
print(f'GCN Model Test RMSE: {rmse:.4f}')

if rmse < naive_rmse:
    print(f"The GCN model (RMSE: {rmse:.4f}) outperforms the Naive Baseline (RMSE: {naive_rmse:.4f}).")
else:
    print(f"The Naive Baseline (RMSE: {naive_rmse:.4f}) performs better or similar to the GCN model (RMSE: {rmse:.4f}).")

"""### Visualizing the GCN Model Architecture

To better understand the `GCNVolatilityForecaster` model, we can visualize its computational graph. We'll use `torchviz` to create a diagram showing the layers and their connections.
"""